include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - flutter/**
    - bin/**
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    # Add project specific lint rules here.