name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.13.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  cloud_firestore: ^6.8.0
  google_generative_ai: ^0.4.0
  fl_chart: ^0.68.0
  intl: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/grindfit_logo.png
    - assets/images/google_logo.png
    - assets/images/fitness_hero.png